---
- name: Configuring apache2
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Edit the index.html file
      copy:
        content: "IntelliQ"
        dest: /var/www/html/index.html
    - name: Restart aapche2
      service:
        name: apache2
        state: restarted
    - name: Check apache respone on server1
      uri:
        url: http://172.31.3.36
        status_code: 200
    - name: Check apache response on server2
      uri:
        url: http://172.31.12.52
        status_code: 200
...





